static const char black[]         = "#282828";
static const char blue[]          = "#d79921"; // focused window border
static const char gray2[]         = "#504945"; // unfocused window border
static const char gray3[]         = "#bdae93";
static const char gray4[]         = "#ebdbb2";
static const char green[]         = "#8ec07c";
static const char orange[]        = "#fe8019";
static const char pink[]          = "#d3869b";
static const char red[]           = "#fb4934";
static const char white[]         = "#ebdbb2";
static const char yellow[]        = "#d79921";
static const char col_borderbar[] = "#1e2122";
